### ISSUE TITLE
Does not display on ubuntu 14.10

### ISSUE THREAD

**Issue by sodrian** [codito/gnome-shell-pomodoro#168]
Hey. 
Installed the extenstion from official repo. Trying to launch gnome-pomodoro starts the process, but nothing in the panel. 
There is a dir /usr/share/gnome-shell/extensions/pomodoro@arun.codito.in with some .js and .css in it.
Thank you.

**Comment by aerostitch** [comment]
Hi @sodrian ,

You will need to use gnome-tweak-tools to enable it on ubuntu.
Can you try it from there please?
Did you logout and log back in after the installation of the package?

Thanks,
Joseph

**Comment by sodrian** [comment]
Yes, I've relogined and restarted pc several times. Also installed gnome-shell-extensions, just to be sure. Still no luck.
As for the gnome-tweak-tools, I tried to use it, google images says there should be "Shell" and "Shell extensions" tabs, none for me.

**Comment by aerostitch** [comment]
Weird. Did you do an `apt-get dist-upgrade` first?
When you say "from official repo" it's from Ubuntu or from the link on the Readme?

**Comment by sodrian** [comment]
apt-get dist-upgrade says nothing, distro is up-to-date
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.10
DISTRIB_CODENAME=utopic
DISTRIB_DESCRIPTION="Ubuntu 14.10"

"from official report" mean aptitude install gnome-shell-pomodoro

root@sodrian-hp-ubuntu:~# dpkg -l gnome
dpkg-query: no packages found matching gnome

root@sodrian-hp-ubuntu:~# dpkg -l gnome-shell-pomodoro
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version           Architecture      Description
+++-=========================-=================-=================-========================================================
ii  gnome-shell-pomodoro      0.10.2-5build1    amd64             GNOME Shell time-management app

**Comment by aerostitch** [comment]
Weird, if I remember correctly version 0.10.2-5 was compatible with gnome 3.12.
I miss-typed the command, can you give me the version of your gnome-shell please? (`dpkg -l gnome-shell`)
It should show up in gnome-tweak-tools if not it means there's either an incompatibility between your gnome-shell version and the package version or an installation issue.
Did you try to purge the package (apt-get purge gnome-shell-pomodoro gnome-shell-pomodoro-data), verify that the /usr/share/gnome-shell/extensions/pomodoro@arun.codito.in folder is removed  and reinstall the package?

**Comment by sodrian** [comment]
Gnome shell version is as follows: gnome-shell               3.12.2-1ubuntu7
Tried to perge and reinstall the extension, still no luck. /usr/share/gnome-shell/extensions/pomodoro@arun.codito.in was not present after the purge.

**Comment by sodrian** [comment]
I noticed the following error, when launching the tweak tool.

    WARNING : Shell not installed or running
    WARNING : Shell not running
    None
    WARNING : Error detecting shell
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 278, in                __init__
        raise Exception("Shell not running or DBus service not available")
    Exception: Shell not running or DBus service not available
    INFO    : GSettings missing key org.gnome.nautilus.desktop (key computer-icon-visible)

**Comment by sodrian** [comment]
Tried to execute the gnome-shell, it's already running.

    ≥ gnome-shell                                                                                                            10:00
   org.gnome.Shell already exists on bus and --replace not specified

**Comment by sodrian** [comment]
On the other hand 
    ≥ /etc/init.d/dbus status                                                                                                10:00
Gives nothing

**Comment by aerostitch** [comment]
Hi @sodrian ,

Are you sure you are running a gnome session and not a default desktop manager session?
In the login screen did you choose "gnome" instead of "ubuntu"?
This application is designed to run on Gnome only for now.

When I go to a Gnome session the timer appears as expected and I can enable/disable it under the "Extensions" section in gnome-tweak-tool.

Thanks,
Joseph

**Comment by sodrian** [comment]
Hi, @aerostitch ,

you are completely right, I've been using default Ubuntu desktop environment.
changing it to Gnome did the trick.

Thanks.
